### ISSUE TITLE
Notfications

### ISSUE THREAD

**Issue by lelmac** [TheOssi/lulu#7]
- Codes/Text
- GCM

**Comment by KaiJanis** [comment]
Tasks:
-talk to S. -> sending Codes or text
-create Creator class
-create ODATA link
-add creator call to the face methods

**Comment by KaiJanis** [comment]
Tasks:
-talk to S. -> sending Codes or text
-create Creator class
-create ODATA link
-add creator call to the face methods
-get GCM links and infos (by S.)

**Comment by kasium** [comment]
- talk to S. -> sending Codes or text
- modify if necessary the gcm seding class (-> custom fields)
- create Creator class
- create ODATA link
- add creator call to the face methods
- get GCM links and infos (by S.)
